import { describe, expect, it } from 'vitest';
import { classifyWebgl2 } from '../gates/corpus-outcome.mjs';
import { frameOf, glslFrameOf, wgslFrame } from '../toy/frame';
import type { WgslFrameGraph } from '@altpsyche/engine';

/**
 * The WebGL 2 corpus column tells a build that *threw* apart from a capability the
 * device *withholds* (item 101).
 *
 * `gates/corpus.mjs` draws every preset's baked GLSL through a real WebGL 2 context,
 * which is a `gate:browser` reading and not run here (§17 note 3). What a node machine
 * *can* settle is the classification the gate makes on the result the page returns:
 * that a throw from the library building the frame is a FAIL, and a refusal from the
 * device linking or drawing it is a SKIP. Before item 101 both were one error shape
 * and both skipped, so item 87's `frameOf` throw — *"names a generated resource 1 with
 * no bytes"* — was reported as a WebGL 2 skip and the gate exited 0 having drawn none
 * of the path it exists to check.
 *
 * This pins the two halves that make that impossible: the pure classifier maps each
 * tag the page returns, and a real `frameOf` throw (item 87's exact shape, reproduced
 * by withholding the generated bytes) lands on the FAIL tag while a real bake-absence
 * (a fullscreen preset `glslFrameOf` cannot carry) lands on the SKIP tag.
 */
describe('the WebGL 2 corpus column tells a build throw apart from a capability refusal (item 101)', () => {
  it('classifies each tag the page returns', () => {
    // A throw from the library building the frame — the gate's own path — is a FAIL.
    expect(classifyWebgl2({ threw: 'names a generated resource 1 with no bytes' }).outcome).toBe('FAIL');
    // A refusal from the backend linking or drawing — the device's path — is a SKIP.
    expect(classifyWebgl2({ refused: 'the program failed to link' }).outcome).toBe('SKIP');
    // The bake carrying no GLSL for this frame is a SKIP.
    expect(classifyWebgl2({ skip: 'the source carried no baked GLSL to draw' }).outcome).toBe('SKIP');
    // No context at all is a SKIP: the device has no path, nothing about the preset.
    expect(classifyWebgl2({ noContext: true }).outcome).toBe('SKIP');
    // A draw that ran but lit nothing is a FAIL — black is indistinguishable from
    // never having drawn — and one that lit is a PASS.
    expect(classifyWebgl2({ lit: 0, total: 480_000 }).outcome).toBe('FAIL');
    expect(classifyWebgl2({ lit: 12_345, total: 480_000 }).outcome).toBe('PASS');
  });

  it('names the throw in the FAIL message and the reason in the SKIP message', () => {
    expect(classifyWebgl2({ threw: 'boom' }).message).toContain('boom');
    expect(classifyWebgl2({ refused: 'no link' }).message).toContain('no link');
  });

  it('a real frameOf throw (item 87 shape) lands on FAIL, where a real bake-absence lands on SKIP', async () => {
    const { loadCorpus } = await import('../gates/lib.mjs');
    const corpus = await loadCorpus();

    // A preset carrying generated geometry: building its frame with the bytes withheld
    // throws exactly as item 87 did — "names a generated resource N with no bytes" —
    // which is the gate's own broken build, so it must FAIL rather than skip.
    const geometry = corpus.find((one) => one.id === 'core-geometry');
    expect(geometry, 'the corpus dropped core-geometry').toBeTruthy();
    const built = (() => {
      try {
        const wgsl = frameOf(geometry!.id, geometry!.description, { wgsl: geometry!.code }, undefined, undefined, new Map());
        glslFrameOf(wgsl as WgslFrameGraph);
        return { lit: 1, total: 1 };
      } catch (error) {
        return { threw: String((error as Error).message).slice(0, 300) };
      }
    })();
    expect(built.threw, 'building core-geometry with no bytes should have thrown').toBeDefined();
    expect(built.threw).toContain('with no bytes');
    expect(classifyWebgl2(built).outcome).toBe('FAIL');

    // A fullscreen frame bakes no vertex, so `glslFrameOf` returns null and the page
    // returns the skip tag — a capability WGSL-fullscreen cannot give WebGL 2, told
    // apart from the build throw above and correctly a SKIP.
    //
    // **The frame is built here rather than taken from the corpus, and that is the
    // point.** This used to reach for `core-texture`, which was fullscreen until
    // item 19 gave it a vertex stage so it would stop being skipped on WebGL 2 and
    // start being compared. Item 19 does the same to the other two, so after it
    // there is no fullscreen preset left to borrow — and there should not be: a
    // corpus preset exists to be drawn by both backends and compared. The
    // *convenience* is still the library's and still works, which is what this
    // classification is about, so the frame to check it with is one written here.
    const fullscreen = wgslFrame(
      'fullscreen-no-vertex',
      '@fragment fn fragMain() -> @location(0) vec4<f32> { return vec4<f32>(1.0); }',
      [{ name: 'u_time', offset: 0, size: 4 }]
    );
    const frame = glslFrameOf(fullscreen as WgslFrameGraph);
    expect(frame, 'a fullscreen WGSL frame names no vertex stage, so it bakes no GLSL').toBeNull();
    const skip = frame ? { lit: 1, total: 1 } : { skip: 'the source carried no baked GLSL to draw' };
    expect(classifyWebgl2(skip).outcome).toBe('SKIP');
  });
});
