import { describe, expect, it } from 'vitest';
import { assembleFrame, cost } from '@altpsyche/engine';
import type { FrameCost } from '@altpsyche/engine';
import { CAPABILITY_FIXTURES } from '../fixtures/capability-fixtures';
import { loadFixture } from './support/fixture';

/**
 * Every corpus preset carries an asserted `cost()` (item 23). Where
 * [tests/cost.test.ts](./cost.test.ts) pins the arithmetic on hand-built frames
 * — one field at a time, on a frame as small as that field needs — this pins the
 * whole metric on the frames the package actually measures itself against, so a
 * change that adds a pass, a pipeline switch, an attachment store or a transient
 * byte to any preset fails here until the number below is updated deliberately.
 * That is the load-bearing property of decision 9: the cost is asserted in CI, on
 * any machine, because it is a fact about a graph's structure rather than
 * anything a card does.
 *
 * The numbers are not a claim about any hardware. They are what `cost()` returns
 * for each preset's graph at the corpus size, produced by running `cost()` in the
 * node suite; a card never enters, and none of these figures is a timing.
 */

/** The size the corpus declares its uniforms at (`u_resolution` is [800, 600]
 * throughout `fixtures/capability-fixtures.ts`), so a frame-sized transient is
 * resolved against the same window the preset is authored for. */
const SIZE = { width: 800, height: 600 };

/** The corpus frame for a preset, assembled the way a loader assembles one: the
 * description off its own source, the generated bytes rekeyed from the address
 * they are fetched by to the resource that reads them, and the uniforms the entry
 * declares. No block is passed because `cost()` reads none — it counts structure,
 * and the uniform block is a layout fact the metric never touches. */
function corpusFrame(id: string) {
  const one = CAPABILITY_FIXTURES.find((fixture) => fixture.id === id)!;
  const { description, code, generated } = loadFixture(id);
  const bytes = new Map<string, Uint8Array<ArrayBuffer>>();
  for (const resource of description.resources) {
    if (!('source' in resource) || !resource.source) continue;
    bytes.set(resource.name, generated.get(resource.source)!);
  }
  const texts = new Map(description.documents.map((document) => [document.name, code]));
  const uniforms = one.uniforms.map((uniform) => ({ name: uniform.name, type: uniform.type }));
  return assembleFrame(id, description, texts, bytes, uniforms);
}

/**
 * The exact cost of every corpus preset at {@link SIZE}. One entry per preset,
 * every field spelled out, so a diff to a preset that changes what the card does
 * shows here as a diff to these numbers. A new preset with no entry fails the
 * coverage test below rather than passing silently uncounted.
 */
const EXPECTED: Record<string, FrameCost> = {
  'core-compute': {
    passes: 1,
    draws: 0,
    dispatches: 1,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 0,
    // The presented picture, frame-sized rgba8: 800 * 600 * 4.
    transientBytes: 1920000,
  },
  'core-texture': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    // The frame target, cleared and presented: one store, no load.
    attachmentStores: 1,
    // The grain texture is uploaded content, so it is resident, not transient.
    transientBytes: 0,
  },
  'core-state': {
    passes: 2,
    draws: 1,
    dispatches: 1,
    pipelineSwitches: 2,
    bindSwitches: 2,
    attachmentLoads: 0,
    attachmentStores: 1,
    // The write half of the ping-pong pair, 256 * 256 rgba8: 262144. The read
    // half carries the prior frame's contents, so it is resident.
    transientBytes: 1048576,
  },
  'core-geometry': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    transientBytes: 0,
  },
  'core-perdraw': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    // The copies buffer is uploaded content, so it is resident.
    transientBytes: 0,
  },
  'core-depth': {
    passes: 2,
    draws: 2,
    dispatches: 0,
    pipelineSwitches: 2,
    // Both passes bind the same resources, so one bind across the two.
    bindSwitches: 1,
    // Second pass loads picture, distance and depth (none cleared): three.
    attachmentLoads: 3,
    // First pass stores picture, distance and depth for the second to read;
    // the second stores the presented picture. distance and depth discard
    // after the second, so 3 + 1 = 4.
    attachmentStores: 4,
    // picture + distance + depth, all frame-sized: 800*600*(4+4+4).
    transientBytes: 5760000,
  },
  'core-target': {
    passes: 2,
    draws: 2,
    dispatches: 0,
    pipelineSwitches: 2,
    bindSwitches: 2,
    attachmentLoads: 0,
    // scene stored for the second pass to sample, then the frame target stored.
    attachmentStores: 2,
    // The scene attachment, frame-sized rgba8.
    transientBytes: 1920000,
  },
  'core-mips': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    // The grain texture is uploaded content, so it is resident.
    transientBytes: 0,
  },
  'core-multisample': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    // The resolve target is the only store; the four-sample source discards.
    attachmentStores: 1,
    // edges (four samples) + flat (one), both frame-sized rgba8:
    // 800*600*4*4 + 800*600*4.
    transientBytes: 9600000,
  },
  'core-indirect': {
    passes: 3,
    draws: 1,
    dispatches: 2,
    pipelineSwitches: 3,
    bindSwitches: 3,
    attachmentLoads: 0,
    attachmentStores: 1,
    // blocks (12) + copies (16) + the ping-pong pair, 256*256 rgba8 twice:
    // 12 + 16 + 262144 * 2.
    transientBytes: 524316,
  },
  'core-report': {
    passes: 2,
    draws: 2,
    dispatches: 0,
    pipelineSwitches: 2,
    bindSwitches: 1,
    // Second pass loads picture and depth: two.
    attachmentLoads: 2,
    // First pass stores picture and depth for the second; second stores the
    // presented picture. depth discards after the second: 2 + 1 = 3.
    attachmentStores: 3,
    // picture + depth (both frame-sized) + took (16) + seen (8):
    // 800*600*(4+4) + 16 + 8.
    transientBytes: 3840024,
  },
  'core-stencil': {
    passes: 2,
    draws: 2,
    dispatches: 0,
    pipelineSwitches: 2,
    bindSwitches: 1,
    // Second pass loads picture and the stencil mask: two.
    attachmentLoads: 2,
    // First pass stores picture and mask for the second; second stores the
    // presented picture. mask discards after the second: 2 + 1 = 3.
    attachmentStores: 3,
    // picture (frame-sized rgba8) + mask (frame-sized stencil8, one byte):
    // 800*600*4 + 800*600*1.
    transientBytes: 2400000,
  },
  'core-scene': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    transientBytes: 0,
  },
  'core-draw-list': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    // The models buffer is uploaded content, so it is resident.
    transientBytes: 0,
  },
  'core-material': {
    passes: 1,
    draws: 1,
    dispatches: 0,
    pipelineSwitches: 1,
    bindSwitches: 1,
    attachmentLoads: 0,
    attachmentStores: 1,
    // The objects buffer is uploaded content, so it is resident.
    transientBytes: 0,
  },
};

describe('the corpus costs', () => {
  it('has an asserted cost for every preset and no cost for a preset that left', () => {
    // Adding a preset with no EXPECTED entry, or leaving an entry for a preset
    // that was removed, fails here — so a new capability fixture cannot land
    // uncounted.
    expect(Object.keys(EXPECTED).sort()).toEqual(CAPABILITY_FIXTURES.map((one) => one.id).sort());
  });

  it.each(CAPABILITY_FIXTURES.map((one) => one.id))('%s costs exactly what decision 9 counts', (id: string) => {
    expect(cost(corpusFrame(id), SIZE)).toEqual(EXPECTED[id]);
  });
});
