import { describe, expect, it } from 'vitest';
import { declaredFrame, geometryFileName } from '../fixtures/shader-describe';
import { CAPABILITY_FIXTURES } from '../fixtures/capability-fixtures';
import { generatedBytes, publishedFrame } from '../fixtures/shader-content';
import type { DeclaredFrame } from '../fixtures/declared-frame';

/**
 * What a declaration asks to be generated, and whether the bytes and the address
 * the description sends a reader to are the same answer.
 *
 * These arrived from the site's build test when the corpus moved. What they hold is
 * the split a declaration is read under: the size is the declaration's and the
 * layout and the format are the generator's, so a run of vertices as long as the
 * primitive it holds is the only thing saying the two agreed about which primitive
 * was asked for.
 */
const drawing = [
  'struct Uniforms { u_time: f32, u_resolution: vec2<f32> };',
  '@group(0) @binding(0) var<uniform> uniforms: Uniforms;',
  'struct Vertex { @builtin(position) at: vec4<f32>, @location(0) place: vec2<f32> };',
  '@vertex',
  'fn warp(@location(0) corner: vec2<f32>, @location(1) place: vec2<f32>) -> Vertex {',
  '  return Vertex(vec4<f32>(corner, 0.0, 1.0), place);',
  '}',
  '@fragment',
  'fn shade(shaded: Vertex) -> @location(0) vec4<f32> {',
  '  return vec4<f32>(shaded.place, uniforms.u_time, 1.0);',
  '}',
].join('\n');

const id = 'fixture-geometry';

const frame: DeclaredFrame = {
  geometry: [{ name: 'grid', primitive: 'quad-grid', size: [4, 4] }],
  passes: [{ pipeline: 'shade', vertex: 'warp', geometry: 'grid', instances: 2 }],
};

describe('what a declaration generates beside a WGSL shader', () => {
  it('makes one run of bytes per buffer, each as long as the primitive it holds', () => {
    const made = generatedBytes(id, frame);

    expect([...made].map(([name, bytes]) => [name, bytes.byteLength])).toEqual([
      ['fixture-geometry-grid.vertices.bin', 25 * 16],
      ['fixture-geometry-grid.indices.bin', 4 * 4 * 6 * 2],
    ]);
  });

  it('makes the same bytes twice over one declaration', () => {
    const first = generatedBytes(id, frame);
    const second = generatedBytes(id, frame);

    expect([...first.values()].map((bytes) => [...bytes])).toEqual([...second.values()].map((bytes) => [...bytes]));
  });

  it('sends the frame to the addresses those bytes were made under', () => {
    const description = declaredFrame(id, drawing, frame);
    const named = description.resources.flatMap((resource) =>
      'source' in resource && resource.source ? [resource.source] : []
    );

    expect(named).toEqual(['fixture-geometry-grid.vertices.bin', 'fixture-geometry-grid.indices.bin']);
  });

  /**
   * A sampled texture and a filled buffer used to get their address and their
   * bytes from one read of one field. Now the declaration carries the address and
   * `generatedBytes` carries the bytes, so the set of names that gets an address
   * and the set that gets bytes are two answers and can hold different names.
   *
   * What this pair catches is a name in one set and not the other: a declaration
   * sent to an address nothing wrote, and bytes written where nothing fetches
   * them. **What it cannot catch is both being wrong the same way**, because
   * `publishedFrame` and `generatedBytes` spell an address through one helper —
   * renaming that helper moves both and these stay green. That is deliberate: one
   * spelling in one place is what leaves only the sets to disagree about. The
   * spelling itself is held by the browser gates, which fetch what the
   * description names.
   *
   * They are here rather than left to those gates because a mismatched set is a
   * fetch that fails in a browser and nowhere else, and that is minutes to find.
   */
  it('sends a fixture to the addresses its own generated bytes were made under', () => {
    for (const one of CAPABILITY_FIXTURES) {
      const made = [...generatedBytes(one.id, one.frame).keys()];
      const declared = publishedFrame(one.id, one.frame);
      const named = [
        ...(declared.textures ?? []).flatMap((texture) => (texture.sampled ? [texture.sampled.source] : [])),
        ...(declared.buffers ?? []).flatMap((buffer) => (buffer.source ? [buffer.source] : [])),
      ];

      for (const address of named) expect(made, `${one.id} declares ${address}`).toContain(address);
    }
  });

  it('declares an address for every picture and every run of numbers it generates', () => {
    // The other direction, which is the failure the one above cannot see: bytes
    // written to an address no declaration sends a reader to are a file the build
    // ships and nothing fetches.
    for (const one of CAPABILITY_FIXTURES) {
      const declared = publishedFrame(one.id, one.frame);
      const named = new Set([
        ...(declared.textures ?? []).flatMap((texture) => (texture.sampled ? [texture.sampled.source] : [])),
        ...(declared.buffers ?? []).flatMap((buffer) => (buffer.source ? [buffer.source] : [])),
        ...(declared.geometry ?? []).flatMap((geometry) => [
          geometryFileName(one.id, geometry.name, 'vertices'),
          geometryFileName(one.id, geometry.name, 'indices'),
        ]),
      ]);

      for (const address of generatedBytes(one.id, one.frame).keys())
        expect([...named], `${one.id} generates ${address}`).toContain(address);
    }
  });
});
