import { describe, expect, it } from 'vitest';
import { createWebGPUBackend } from '../gpu/webgpu';
import { frameOf } from '@altpsyche/engine';
import type { FrameGraph } from '@altpsyche/engine';
import { createFakeGPU } from './support/fake-gpu';
import { loadFixture } from './support/fixture';

/**
 * The sampling preset as the build wrote it, drawn against the recording device.
 *
 * The description, the source and the picture come from a fixture this package
 * owns, so the test runs anywhere the library does. They are still not written
 * beside the assertions, which would only ever say the backend agrees with the
 * test: the fixture is what a build produced, and a check on the site side holds
 * that build against these files, so drift is caught by whoever owns the build.
 */
const { description, code, generated } = loadFixture('core-texture');

/**
 * The generated bytes by the index of the resource that names them, which is the
 * shape `frameOf` wants (item 87). `loadFixture` keys them by the file name the
 * build wrote, so the join is each resource's own `source`.
 *
 * **This file used to reach for `loadPictureFixture` and hand over
 * `new Map([[1, bytes]])`.** Both stopped working at item 19, when the preset
 * gained a quad covering the frame so that it draws its own corners and stops
 * being skipped on WebGL 2: that helper insists a fixture generates exactly one
 * thing, and this frame now generates three. The picture is still resource 1 —
 * what was wrong was writing down one index and one resource by hand when the
 * description says both.
 */
const generatedByIndex = new Map(
  description.resources.flatMap((resource, index) =>
    'source' in resource && resource.source ? [[index, generated.get(resource.source)!] as const] : []
  )
);

/** The picture itself, for the assertions about its size and its bytes. */
const pictureIndex = description.resources.findIndex((resource) => resource.kind === 'texture');
const bytes = generatedByIndex.get(pictureIndex)!;

const WIDTH = 800;
const HEIGHT = 600;

function drawn(): ReturnType<typeof createFakeGPU> {
  const gpu = createFakeGPU();
  const backend = createWebGPUBackend(gpu.canvas, gpu.device);
  if (!backend) throw new Error('the fake canvas gave no WebGPU context');
  const frame: FrameGraph = frameOf(
    'core-texture',
    description,
    { wgsl: code },
    [
      { name: 'u_time', offset: 0, size: 4 },
      { name: 'u_resolution', offset: 8, size: 8 },
    ],
    undefined,
    // Every generated resource, keyed by its index (item 87) — the picture and,
    // since item 19, the vertices and indices of the quad it draws over.
    generatedByIndex
  );
  backend.resize(WIDTH, HEIGHT);
  backend.program(frame).draw();
  return gpu;
}

describe('the sampling preset the build wrote', () => {
  it('is one render pass over the quad it declares, and no compute pass at all', () => {
    const gpu = drawn();
    expect(gpu.calls('beginRenderPass')).toHaveLength(1);
    expect(gpu.calls('beginComputePass')).toHaveLength(0);

    // **This used to assert `draw` with a count of 3** — the backend's own three
    // corners, which a pipeline naming no vertex stage gets. Item 19 gave the
    // preset a vertex stage over a quad of its own, because a pipeline with no
    // vertex stage bakes no GLSL vertex and `gates/corpus.mjs` skipped this preset
    // on WebGL 2 entirely: a preset whose whole purpose is to be compared across
    // the two backends was being drawn by one. So the draw is indexed now, over
    // the quad's two triangles.
    expect(gpu.calls('draw')).toHaveLength(0);
    expect(gpu.calls('drawIndexed')[0]).toMatchObject({ count: 6 });
  });

  it('hands the card the picture the build wrote, whole, at four bytes a pixel', () => {
    const gpu = drawn();
    expect(bytes).toHaveLength(64 * 64 * 4);
    expect(gpu.calls('writeTexture')).toEqual([
      { call: 'writeTexture', label: 'texture1', bytes: bytes.length, stride: 64 * 4, size: [64, 64] },
    ]);
  });

  it('makes the picture at its own size rather than the frame’s, so a resize leaves it alone', () => {
    const gpu = drawn();
    const made = gpu.calls('createTexture').find((call) => call.label === 'texture1');
    expect(made).toMatchObject({ size: [64, 64], format: 'rgba8unorm' });
    expect(gpu.calls('createTexture').find((call) => call.label === 'frame')).toMatchObject({ size: [800, 600] });
  });

  it('makes the sampler the entry chose rather than the card’s default', () => {
    expect(drawn().calls('createSampler')[0]).toMatchObject({
      label: 'sampler2',
      magFilter: 'linear',
      addressModeU: 'repeat',
      addressModeV: 'repeat',
    });
  });

  it('binds the block, the view and the sampler at the numbers the source declares', () => {
    expect(drawn().calls('createBindGroup')[0]!.bindings).toEqual([
      { binding: 0, resource: 'uniforms' },
      { binding: 1, resource: 'texture1.view' },
      { binding: 2, resource: 'sampler2' },
    ]);
  });

  it('declares all three to the fragment stage alone, since the vertex half reads nothing', () => {
    expect(drawn().calls('createBindGroupLayout')[0]!.entries).toEqual([
      { binding: 0, visibility: GPUShaderStage.FRAGMENT, kind: 'buffer:uniform' },
      { binding: 1, visibility: GPUShaderStage.FRAGMENT, kind: 'texture' },
      { binding: 2, visibility: GPUShaderStage.FRAGMENT, kind: 'sampler' },
    ]);
  });

  it('draws into the frame’s own target rather than naming a picture to copy out', () => {
    expect(description.present).toBeUndefined();
    expect(drawn().calls('copyTextureToTexture')).toHaveLength(0);
  });
});
