import { readFileSync } from 'node:fs';
import path from 'node:path';
import type { FrameDescription } from '@altpsyche/engine';
import { CAPABILITY_FIXTURES } from '../../fixtures/capability-fixtures';
import { declaredFrame, generatedBytes } from '../../fixtures/shader-describe';

/**
 * A shader a backend test draws, derived from a source and a declaration this
 * package owns rather than read out of a website's build directory.
 *
 * Nothing about a fixture is stored. The source is a file here, the frame is
 * declared beside it, and the description and every generated byte are worked out
 * when a test asks for them, by the same code that would describe any shader. So a
 * fixture cannot drift from what the library does, there is nothing to keep
 * current, and a clone of this package with nothing else on the machine can
 * reproduce its whole corpus.
 *
 * That is what replaced a pair of committed JSON files. What those cost was a
 * check that had to run wherever the build that wrote them lived, so the library
 * carried data it could not reproduce and somebody else's repository had to say
 * whether it was still right.
 */
export interface Fixture {
  description: FrameDescription;
  code: string;
  /** Everything the declaration asked to be generated, keyed by the address the
   * description sends a reader to. Empty for a fixture that generates nothing. */
  generated: Map<string, Uint8Array<ArrayBuffer>>;
}

/** A fixture whose frame samples a picture, so its bytes are the reason it exists.
 * Separating the two keeps a caller that needs the bytes from testing whether they
 * arrived: the fixture either generates exactly one thing and this is what it
 * returns, or asking for them is the error rather than the empty answer. */
export interface PictureFixture extends Fixture {
  bytes: Uint8Array<ArrayBuffer>;
}

export const FIXTURES = CAPABILITY_FIXTURES.map((one) => one.id);

export type FixtureName = (typeof CAPABILITY_FIXTURES)[number]['id'];

/** Where the sources live, so a gate reading one spells the path the same way this
 * does rather than a second time. */
export function sourcePath(name: FixtureName): string {
  const one = CAPABILITY_FIXTURES.find((fixture) => fixture.id === name);
  if (!one) throw new Error(`there is no fixture called "${name}"`);
  return path.join(import.meta.dirname, '..', '..', 'fixtures', 'source', one.source);
}

export function loadFixture(name: FixtureName): Fixture {
  const one = CAPABILITY_FIXTURES.find((fixture) => fixture.id === name);
  if (!one) throw new Error(`there is no fixture called "${name}"`);
  const code = readFileSync(sourcePath(name), 'utf-8');
  return {
    description: declaredFrame(one.id, code, one.frame),
    code,
    generated: generatedBytes(one.id, one.frame),
  };
}

export function loadPictureFixture(name: FixtureName): PictureFixture {
  const fixture = loadFixture(name);
  const made = [...fixture.generated.values()];
  if (made.length !== 1)
    throw new Error(`the fixture "${name}" generates ${made.length} things rather than one picture`);
  return { ...fixture, bytes: made[0]! };
}
